Repository basementdevs/twitch-addon-scylladb-rs, pull requests merged in 2024-08, with the labels that each got.

#7 feat: add plasmo environment variables
  extension/.env.example
  extension/.gitignore
  extension/package.json
  extension/pnpm-lock.yaml
  extension/src/background/messages/oauth.ts
  extension/src/config/env.ts
  extension/src/content.ts
  extension/tsconfig.json
Labels: enhancement, javascript/typescript

#18 feat(linters): add linters and formatters to the project
  api/README.md
  api/rustfmt.toml
  api/src/config/app.rs
  api/src/config/mod.rs
  api/src/http/messages_controller.rs
  api/src/http/mod.rs
  api/src/http/settings_controller.rs
  api/src/main.rs
  api/src/models/materialized_views/mod.rs
  api/src/models/materialized_views/settings_by_username.rs
  api/src/models/message.rs
  api/src/models/mod.rs
  api/src/models/settings.rs
  api/tests/http/settings_controller_test.rs
  extension/.prettierrc.mjs
  extension/biome.jsonc
  extension/components.json
  extension/package.json
  extension/pnpm-lock.yaml
  extension/postcss.config.js
  extension/src/background/index.ts
  extension/src/background/messages/oauth.ts
  extension/src/config/env.ts
  extension/src/content.ts
  extension/src/popup.tsx
  extension/src/resources/components/app/header.tsx
  extension/src/resources/components/app/mode-toggle.tsx
  extension/src/resources/components/app/theme-provide.tsx
  extension/src/resources/components/auth/authenticate-button.tsx
  extension/src/resources/components/auth/hero.tsx
  extension/src/resources/components/settings/profile-card.tsx
  extension/src/resources/components/settings/settings-form.tsx
  extension/src/resources/pages/auth.tsx
  extension/src/resources/pages/profile.tsx
  extension/src/resources/shad/components/ui/button.tsx
  extension/src/resources/shad/components/ui/card.tsx
  extension/src/resources/shad/components/ui/dialog.tsx
  extension/src/resources/shad/components/ui/dropdown-menu.tsx
  extension/src/resources/shad/components/ui/input.tsx
  extension/src/resources/shad/components/ui/label.tsx
  extension/src/resources/shad/components/ui/typography/h1.tsx
  extension/src/resources/shad/components/ui/typography/h2.tsx
  extension/src/resources/shad/components/ui/typography/h3.tsx
  extension/src/resources/shad/components/ui/typography/h4.tsx
  extension/src/resources/shad/lib/utils.ts
  extension/src/scripting/components.ts
  extension/src/scripting/index.ts
  extension/src/scripting/observer.ts
  extension/src/scripting/queue.ts
  extension/src/types/types.d.ts
  extension/src/utils/i18nUtils.ts
  extension/tailwind.config.js
Labels: enhancement

#34 feat(header): add extension version on header
  extension/src/resources/components/app/header.tsx
  extension/tsconfig.json
Labels: extension
